---
# Author: Lincolm Ferreira de  Aguiar
# e-mail: lifaguiar@outlook.com
configs:
   instances: 1
   name_prefix: "core"
   image:
      update_channel: "alpha"
      version: "current"
      serial_logging: false
   share_home: false
   gui: false
   memory: 8192
   cpus: 2
   network_prefix: "19.8.206"
   domain: "lincolmlabs.dev"
   local_registry: "swarm-master.lincolmlabs.cloud:5000"
   execution_cap: 75